# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/true_color_dot_led/true_color_dot_led.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==true_color_dot_led || ORIG_REF_NAME==true_color_dot_led}]

# IP: bd/true_color_dot_led/ip/true_color_dot_led_true_color_dot_led_0_0/true_color_dot_led_true_color_dot_led_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==true_color_dot_led_true_color_dot_led_0_0 || ORIG_REF_NAME==true_color_dot_led_true_color_dot_led_0_0}]

# IP: bd/true_color_dot_led/ip/true_color_dot_led_blk_mem_gen_0_0/true_color_dot_led_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==true_color_dot_led_blk_mem_gen_0_0 || ORIG_REF_NAME==true_color_dot_led_blk_mem_gen_0_0}]

# IP: bd/true_color_dot_led/ip/true_color_dot_led_xlslice_0_0/true_color_dot_led_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==true_color_dot_led_xlslice_0_0 || ORIG_REF_NAME==true_color_dot_led_xlslice_0_0}]

# IP: bd/true_color_dot_led/ip/true_color_dot_led_processing_system7_0_1/true_color_dot_led_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==true_color_dot_led_processing_system7_0_1 || ORIG_REF_NAME==true_color_dot_led_processing_system7_0_1}]

# IP: bd/true_color_dot_led/ip/true_color_dot_led_processing_system7_0_axi_periph_1/true_color_dot_led_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==true_color_dot_led_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==true_color_dot_led_processing_system7_0_axi_periph_1}]

# IP: bd/true_color_dot_led/ip/true_color_dot_led_rst_processing_system7_0_100M_1/true_color_dot_led_rst_processing_system7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==true_color_dot_led_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==true_color_dot_led_rst_processing_system7_0_100M_1}]

# IP: bd/true_color_dot_led/ip/true_color_dot_led_xbar_1/true_color_dot_led_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==true_color_dot_led_xbar_1 || ORIG_REF_NAME==true_color_dot_led_xbar_1}]

# IP: bd/true_color_dot_led/ip/true_color_dot_led_xlconcat_0_0/true_color_dot_led_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==true_color_dot_led_xlconcat_0_0 || ORIG_REF_NAME==true_color_dot_led_xlconcat_0_0}]

# IP: bd/true_color_dot_led/ip/true_color_dot_led_auto_pc_0/true_color_dot_led_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==true_color_dot_led_auto_pc_0 || ORIG_REF_NAME==true_color_dot_led_auto_pc_0}]

# XDC: bd/true_color_dot_led/ip/true_color_dot_led_blk_mem_gen_0_0/true_color_dot_led_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/true_color_dot_led/ip/true_color_dot_led_processing_system7_0_1/true_color_dot_led_processing_system7_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==true_color_dot_led_processing_system7_0_1 || ORIG_REF_NAME==true_color_dot_led_processing_system7_0_1}] {/inst }]/inst ]]

# XDC: bd/true_color_dot_led/ip/true_color_dot_led_rst_processing_system7_0_100M_1/true_color_dot_led_rst_processing_system7_0_100M_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==true_color_dot_led_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==true_color_dot_led_rst_processing_system7_0_100M_1}] {/U0 }]/U0 ]]

# XDC: bd/true_color_dot_led/ip/true_color_dot_led_rst_processing_system7_0_100M_1/true_color_dot_led_rst_processing_system7_0_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==true_color_dot_led_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==true_color_dot_led_rst_processing_system7_0_100M_1}] {/U0 }]/U0 ]]

# XDC: bd/true_color_dot_led/ip/true_color_dot_led_rst_processing_system7_0_100M_1/true_color_dot_led_rst_processing_system7_0_100M_1_ooc.xdc

# XDC: bd/true_color_dot_led/ip/true_color_dot_led_xbar_1/true_color_dot_led_xbar_1_ooc.xdc

# XDC: bd/true_color_dot_led/ip/true_color_dot_led_auto_pc_0/true_color_dot_led_auto_pc_0_ooc.xdc

# XDC: bd/true_color_dot_led/true_color_dot_led_ooc.xdc
