# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.cache/wt [current_project]
set_property parent.project_path /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/chibiegg/vivado/projects/zynq-true-color-dotled/ip_repo/true_color_dot_led/true_color_dot_led_1.0 [current_project]
add_files /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/default_vram.coe
add_files /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/sources_1/bd/true_color_dot_led/true_color_dot_led.bd
set_property used_in_implementation false [get_files -all /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/sources_1/bd/true_color_dot_led/ip/true_color_dot_led_blk_mem_gen_0_0/true_color_dot_led_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/sources_1/bd/true_color_dot_led/ip/true_color_dot_led_processing_system7_0_1/true_color_dot_led_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/sources_1/bd/true_color_dot_led/ip/true_color_dot_led_rst_processing_system7_0_100M_1/true_color_dot_led_rst_processing_system7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/sources_1/bd/true_color_dot_led/ip/true_color_dot_led_rst_processing_system7_0_100M_1/true_color_dot_led_rst_processing_system7_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/sources_1/bd/true_color_dot_led/ip/true_color_dot_led_rst_processing_system7_0_100M_1/true_color_dot_led_rst_processing_system7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/sources_1/bd/true_color_dot_led/ip/true_color_dot_led_xbar_1/true_color_dot_led_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/sources_1/bd/true_color_dot_led/ip/true_color_dot_led_auto_pc_0/true_color_dot_led_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/sources_1/bd/true_color_dot_led/true_color_dot_led_ooc.xdc]
set_property is_locked true [get_files /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/sources_1/bd/true_color_dot_led/true_color_dot_led.bd]

read_verilog -library xil_defaultlib /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/sources_1/bd/true_color_dot_led/hdl/true_color_dot_led_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files /home/chibiegg/vivado/projects/zynq-true-color-dotled/true-color-dotled/true-color-dotled.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top true_color_dot_led_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef true_color_dot_led_wrapper.dcp

catch { report_utilization -file true_color_dot_led_wrapper_utilization_synth.rpt -pb true_color_dot_led_wrapper_utilization_synth.pb }
